/*
tuya_iot_config.h
Copyright(C),2018-2020, 涂鸦科技 www.tuya.comm
*/

/* AUTO-GENERATED FILE. DO NOT MODIFY !!!
*
* This config file is automatically generated by tuya cross-build system.
* It should not be modified by hand.
*/

#ifndef TUYA_IOT_CONFIG_H
#define TUYA_IOT_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

/* default definitons */

#define SYSTEM_SMALL_MEMORY_BEGIN       0       /*small memory systems begin */
#define SYSTEM_REALTEK8710_1M           1
#define SYSTEM_REALTEK8710_2M           2
#define SYSTEM_NON_OS					3		/*no operating system*/
#define SYSTEM_FREERTOS                 98
#define SYSTEM_SMALL_MEMORY_END         99      /*small memory systems end */
#define SYSTEM_LINUX                    100
#define SYSTEM_LITEOS                   120

#define TLS_DISABLE                     0       /* disable tls function */
#define TLS_TUYA_PSK_ONLY               2       /* only enable ciper 0xAE */
#define TLS_TUYA_ECC_PSK                3       /* enable ciper 0xAE && 0xC027 */
#define TLS_TUYA_ECC_ONLY               4       /* only enable ciper 0xC027 */
#define TLS_TUYA_ECC_ONLY_NOSTRIP       5       /* only enable ciper 0xC027, but enable most of mbed-tls configs */
#define TLS_TUYA_ECC_CLIENT_AUTH        6       /* TLS Client Authentication and Server Authentication mode */

#define TUYA_SL_0           0       /* security level 0,Applies to: Resource-constrained devices;Feature: Can only access Tuya Cloud */
#define TUYA_SL_1           1       /* security level 1,Applies to: Resource-constrained devices;Feature: One-way authentication */
#define TUYA_SL_2           2       /* security level 2,Applies to: Resource-rich equipment;Feature: Two-way authentication */
#define TUYA_SL_3           3       /* security level 3,Applies to: Resource-rich equipment;Feature: Two-way authentication,Devices use security chips to protect sensitive information */
#define TUYA_MODIFY_MBEDTLS             1

#define TUYA_OPERATOR_DISABLE           0x0
#define TUYA_OPERATOR_CUCC              0x01
#define TUYA_OPERATOR_CTCC              0x02
#define TUYA_OPERATOR_CMCC              0x04
#define TUYA_OPERATOR_CMCC_ANDLINK      0x08
#define TUYA_OPERATOR_ALL               (TUYA_OPERATOR_CUCC | TUYA_OPERATOR_CTCC | TUYA_OPERATOR_CMCC)


#define TUYA_LAN_V31              0x1
#define TUYA_LAN_V32              0x2
#define TUYA_LAN_V33              0x4
#define TUYA_LAN_V35              0x8
#define TUYA_LAN_ALL              (TUYA_LAN_V31 | TUYA_LAN_V32 | TUYA_LAN_V33 | TUYA_LAN_V35)

#define TUYA_MQ_V21               0x1
#define TUYA_MQ_V22               0x2
#define TUYA_MQ_V23               0x4
#define TUYA_MQ_ALL               (TUYA_MQ_V21 | TUYA_MQ_V22 | TUYA_MQ_V23)

/* custom settings */
#define BUILD_DATE           "2023_09_14"
#define BUILD_TIME           "15_21_14"
#define GIT_USER             "ci_manage"
#define IOT_SDK_VER          "3.6.111"
#define SDK_BETA_VER         "beta.11"
#define TARGET_PLATFORM      "esp32"
#define PROJECT_NAME         "tuyaos-iot"
#define SDK_ID               "tuyaos-iot_3.6.111-beta.11_esp32_esp32s3_1.0.32"
#define KERNEL_VER	        "1.0.1-beta.33"
// Generated by Tuya (https://www.tuya.com)
// 基于项目 tuyaos-iot (3.6.111-beta.8)
// 基于工具链 esp32 (1.0.29)


#define ENABLE_LOG 1

#define STACK_SIZE_TIMERQ 4096

// CONFIG_ENABLE_NETWORK_OPTIONS is not set


#define STACK_SIZE_HEALTH_MONITOR 4096

#define ENABLE_OSS_COMPILE_WARNINGS 1



#define ESPIDFV44 1

// CONFIG_ESPIDFV50 is not set

// CONFIG_ESPIDFV51 is not set


// CONFIG_ESP32 is not set

// CONFIG_ESP32C2 is not set

// CONFIG_ESP32C3 is not set

// CONFIG_ESP32C6 is not set

// CONFIG_ESP32S2 is not set

#define ESP32S3 1

// CONFIG_ESP32H2 is not set


// CONFIG_KV_PROTECTED_ENABLE is not set

// CONFIG_ENABLE_KV_FILE is not set

// CONFIG_ENABLE_KV_PROTECTED is not set

// CONFIG_ENABLE_KV_KEY_SEED is not set


// CONFIG_ENABLE_UF_HUGE_FILE is not set

#define MAX_LENGTH_OF_FILE_FULL_PATH 128


#define EVENT_NAME_MAX_LEN 16

// CONFIG_ENABLE_TUYA_LAN is not set


#define STACK_SIZE_UPGRADE 4096

// CONFIG_ENABLE_FIRMWARE_SIGN_TUYA is not set

// CONFIG_ENABLE_FIRMWARE_SIGN_USER is not set


// CONFIG_ENABLE_PRODUCT_AUTOTEST is not set

#define STACK_SIZE_MF_TEST 8192

// CONFIG_ENABLE_LWIP is not set

#define ENABLE_BT_SERVICE 1

#define ENABLE_BT_NETCFG 1

// CONFIG_ENABLE_BT_ACTIVE is not set

// CONFIG_ENABLE_BT_CTRL is not set

#define BT_ADV_INTERVAL_MIN 30

#define BT_ADV_INTERVAL_MAX 60

// CONFIG_ENABLE_BT_REMOTE_CTRL is not set

#define BT_REMOTE_CTRL_SCAN_INTERVAL 30

#define BT_REMOTE_CTRL_SCAN_WINDOWS 10

#define ENABLE_BT_TIMER 1

#define ENABLE_BT_MF 1

#define ENABLE_MF_BY_BT 1

// CONFIG_ENABLE_BT_VIRTUAL is not set

#define TUYA_BLE_VER 4

#define ENABLE_TAL_BLUETOOTH 1

#define TAL_BLUETOOTH 1

#define TAL_BLE_SERVICE_VERSION 2

#define ENABLE_TUYA_BLE_STACK 1

#define TARGET_BT_PLATFORM 2

#define TUYA_HS_BLE_HOST_TASK_PRIORITY 9

#define TUYA_HS_BLE_HOST_STACK_SIZE 5120

#define TY_BT_MOD 1

#define BT_NETCFG 1

// CONFIG_BT_ACTIVE is not set

// CONFIG_BT_CTRL is not set

// CONFIG_BT_REMOTE_CTRL is not set

#define BT_TIMER 1

#define MF_BT 1

// CONFIG_BT_VIRTUAL is not set

#define WIFI_GW 1

// CONFIG_TUYA_HOSTAPD_SUPPORT is not set

#define ENABLE_WIFI_SERVICE 1

// CONFIG_ENABLE_WIFI_EZ is not set

// CONFIG_ENABLE_WIFI_FFS is not set

// CONFIG_ENABLE_WIFI_PEGASUS is not set

#define ENABLE_WIFI_PROTECT 1

// CONFIG_ENABLE_WIFI_FFC is not set

// CONFIG_ENABLE_HOSTAPD is not set

#define ENABLE_STATION_AP_MODE 0

#define WIFI_AP_BUF_SIZE 10240

// CONFIG_QRCODE_ACTIVE_MODE is not set

#define ENABLE_TUYA_CLOUD 1

#define ENABLE_ASTRO_TIMER 1

#define ENABLE_CALENDAR_TIMER 1

// CONFIG_ENABLE_QRCODE_ACTIVE is not set

#define ENABLE_DEVICE_DATA_COLLECT 1

// CONFIG_ENABLE_LOCAL_KEY_UPDATE is not set

#define ENABLE_COMMUNICATE_PRIORITY 1


// CONFIG_ENABLE_BLACK_WHITE_LIST is not set

#define MAX_SECURITY_LEVEL 1

#define TUYA_SECURITY_LEVEL 1

// CONFIG_ENABLE_MBEDTLS_DEBUG is not set

#define ENABLE_CUSTOM_CONFIG 1

#define ENABLE_MBEDTLS_SSL_MAX_FRAGMENT_LENGTH 1

// CONFIG_ENABLE_MBEDTLS_CLIENT_SSL_SESSION_TICKETS is not set

#define ENABLE_MBEDTLS_SSL_MAX_CONTENT_LEN 5120

// CONFIG_ENABLE_MBEDTLS_HAVE_TIME is not set

// CONFIG_ENABLE_MBEDTLS_FS_IO is not set

// CONFIG_ENABLE_MBEDTLS_NET_C is not set

// CONFIG_ENABLE_MBEDTLS_HAVEGE_C is not set

// CONFIG_ENABLE_MBEDTLS_TIMING_C is not set

// CONFIG_ENABLE_MBEDTLS_ARC4_C is not set


// CONFIG_ENABLE_MBEDTLS_DES_C is not set

// CONFIG_ENABLE_MBEDTLS_CAMELLIA_C is not set

// CONFIG_ENABLE_MBEDTLS_BLOWFISH_C is not set

// CONFIG_ENABLE_MBEDTLS_XTEA_C is not set

#define ENABLE_MBEDTLS_CCM_C 1

#define ENABLE_MBEDTLS_GCM_C 1


#define ENABLE_MBEDTLS_RSA_C 1

// CONFIG_ENABLE_MBEDTLS_GENPRIME is not set

#define ENABLE_MBEDTLS_DHM_C 1

#define ENABLE_MBEDTLS_ECP_C 1

// CONFIG_ENABLE_MBEDTLS_PK_C is not set

#define ENABLE_MBEDTLS_ECDH_C 1

// CONFIG_ENABLE_MBEDTLS_ECDSA_C is not set

// CONFIG_ENABLE_MBEDTLS_ECP_DP_SECP192R1_ENABLED is not set

// CONFIG_ENABLE_MBEDTLS_ECP_DP_SECP224R1_ENABLED is not set

#define ENABLE_MBEDTLS_ECP_DP_SECP256R1_ENABLED 1

// CONFIG_ENABLE_MBEDTLS_ECP_DP_SECP384R1_ENABLED is not set

// CONFIG_ENABLE_MBEDTLS_ECP_DP_SECP521R1_ENABLED is not set

// CONFIG_ENABLE_MBEDTLS_ECP_DP_SECP192K1_ENABLED is not set

// CONFIG_ENABLE_MBEDTLS_ECP_DP_SECP224K1_ENABLED is not set

// CONFIG_ENABLE_MBEDTLS_ECP_DP_SECP256K1_ENABLED is not set

// CONFIG_ENABLE_MBEDTLS_ECP_DP_BP256R1_ENABLED is not set

// CONFIG_ENABLE_MBEDTLS_ECP_DP_BP384R1_ENABLED is not set

// CONFIG_ENABLE_MBEDTLS_ECP_DP_BP512R1_ENABLED is not set

// CONFIG_ENABLE_MBEDTLS_ECP_DP_CURVE25519_ENABLED is not set

// CONFIG_ENABLE_MBEDTLS_ECP_DP_CURVE448_ENABLED is not set

#define ENABLE_MBEDTLS_ECP_NIST_OPTIM 1

// CONFIG_ENABLE_MBEDTLS_ECP_RESTARTABLE is not set


// CONFIG_ENABLE_MBEDTLS_X509_CRT is not set

// CONFIG_ENABLE_MBEDTLS_CHACHA20_C is not set

// CONFIG_ENABLE_MBEDTLS_CMAC_C is not set

// CONFIG_ENABLE_MBEDTLS_HMAC_DRBG_C is not set

// CONFIG_ENABLE_MBEDTLS_POLY1305_C is not set

// CONFIG_ENABLE_MBEDTLS_RIPEMD160_C is not set

#define MBEDTLS_TLS_MODE ENABLE_MBEDTLS_TLS_CLIENT_ONLY

// CONFIG_ENABLE_MBEDTLS_TLS_SERVER_AND_CLIENT is not set

// CONFIG_ENABLE_MBEDTLS_TLS_SERVER_ONLY is not set

#define ENABLE_MBEDTLS_TLS_CLIENT_ONLY 1

// CONFIG_ENABLE_MBEDTLS_TLS_DISABLED is not set

// CONFIG_ENABLE_MBEDTLS_SSL_SRV_C is not set

#define ENABLE_MBEDTLS_SSL_CLI_C 1

#define MBEDTLS_TLS_ENABLED 1

// CONFIG_ENABLE_MBEDTLS_SSL_PROTO_TLS1 is not set

// CONFIG_ENABLE_MBEDTLS_SSL_PROTO_TLS1_1 is not set

#define ENABLE_MBEDTLS_SSL_PROTO_TLS1_2 1

#define ENABLE_MBEDTLS_SSL_PROTO_DTLS 1

#define ENABLE_MBEDTLS_SSL_DTLS_HELLO_VERIFY 1

#define ENABLE_ENABLE_SSL_DTLS_SRTP 1


#define ENABLE_MBEDTLS_PSK_MODES 1

#define ENABLE_MBEDTLS_KEY_EXCHANGE_PSK 1

#define ENABLE_MBEDTLS_KEY_EXCHANGE_DHE_PSK 1

#define ENABLE_MBEDTLS_KEY_EXCHANGE_ECDHE_PSK 1

// CONFIG_ENABLE_MBEDTLS_KEY_EXCHANGE_RSA_PSK is not set

// CONFIG_ENABLE_MBEDTLS_KEY_EXCHANGE_RSA is not set

// CONFIG_ENABLE_MBEDTLS_KEY_EXCHANGE_DHE_RSA is not set

#define ENABLE_MBEDTLS_KEY_EXCHANGE_ELLIPTIC_CURVE 1

#define ENABLE_MBEDTLS_KEY_EXCHANGE_ECDHE_RSA 1

// CONFIG_ENABLE_MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA is not set

// CONFIG_ENABLE_MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA is not set

#define ENABLE_MBEDTLS_KEY_EXCHANGE_ECDH_RSA 1


#define HTTP_MAX_REQ_RESP_HDR_SIZE 4096

#define MAX_HTTP_SESSION_NUM 16


#define TUYA_MQ_VERSION 0x4

#define STACK_SIZE_MQTT_CLIENT 8192

#define QOS1_PUBACK_TIMEOUT 3

#define QOS1_PUBLISH_SLOT_CNT 8

#define QOS1_PUBACK_TIMEOUT_LIMIT 3

#define MAX_RANDOM_DELAY_BEFORE_RECONNECT 300

#define MQTT_HEATBEAT_INTERVAL 60

#define MQTT_RECV_BUF_SIZE 512

#define MQTT_MAX_MESSGAE_SIZE 5120

#define MQTT_RECV_SELECT_TIMEOUT 3000

// CONFIG_ENABLE_MQTT_QOS1_RESEND is not set

// CONFIG_TUYA_IOT_DEBUG is not set


#define STACK_SIZE_WORK_QUEUE 8192

#define MAX_NODE_NUM_WORK_QUEUE 100

#define STACK_SIZE_MSG_QUEUE 5120

#define MAX_NODE_NUM_MSG_QUEUE 100

// CONFIG_ENABLE_IOT_DEBUG is not set

#define TUYA_REDUCE_BIN 0

#define ENABLE_WEBSOCKET 1


#define OPERATING_SYSTEM 98

#define LITTLE_END 1

#define ENABLE_FILE_SYSTEM 1

// CONFIG_ENABLE_RTC is not set

#define ENABLE_ADC 1

#define ENABLE_UART 1

// CONFIG_ENABLE_UART_INTERRUPT is not set

#define ENABLE_WATCHDOG 1

#define ENABLE_FLASH 1

#define TUYA_FLASH_TYPE_MAX_PARTITION_NUM 10

#define ENABLE_PWM 1

#define ENABLE_GPIO 1

#define ENABLE_I2C 1

#define ENABLE_SPI 1

// CONFIG_ENABLE_ZIGBEE is not set

#define ENABLE_WIFI 1

// CONFIG_ENABLE_WIRED is not set

// CONFIG_ENABLE_TIMER is not set

// CONFIG_ENABLE_BLUETOOTH is not set

// CONFIG_ENABLE_HCI is not set

// CONFIG_ENABLE_DISPLAY is not set

// CONFIG_ENABLE_MEDIA is not set

// CONFIG_ENABLE_PM is not set

// CONFIG_GPRS_GW is not set

// CONFIG_TUYA_CAT1 is not set

// CONFIG_ENABLE_CELLULAR is not set

// CONFIG_ENABLE_STORAGE is not set

// CONFIG_ENABLE_NB is not set

// CONFIG_ENABLE_REGISTER is not set

// CONFIG_ENABLE_DAC is not set

#define ENABLE_I2S 1

#define ENABLE_PINMUX 1

// CONFIG_ENABLE_PIN2FUNC is not set

// CONFIG_ENABLE_PLATFORM_AES is not set

// CONFIG_ENABLE_PLATFORM_SHA256 is not set

// CONFIG_ENABLE_PLATFORM_MD5 is not set

// CONFIG_ENABLE_PLATFORM_SHA1 is not set

// CONFIG_ENABLE_PLATFORM_RSA is not set

// CONFIG_ENABLE_PLATFORM_ECC is not set

// CONFIG_ENABLE_WAKEUP is not set
#ifndef TUYA_LAN_VERSION
#define TUYA_LAN_VERSION TUYA_LAN_V35
#endif

#ifndef TUYA_MQ_VERSION
#define TUYA_MQ_VERSION TUYA_MQ_V23
#endif

#ifndef ENABLE_DEVICE_DATA_COLLECT
#define ENABLE_DEVICE_DATA_COLLECT 0
#endif

#ifndef TUYA_WEAK_ATTRIBUTE
#define TUYA_WEAK_ATTRIBUTE __attribute__ ((weak))
#endif

/* custom settings */

#ifdef __cplusplus
}
#endif


#endif
